### ISSUE TITLE
Unhandled System.NullReferenceException in ClientConnected event handler

### ISSUE THREAD

**Issue by SaintedPsycho** [jchristn/HttpServerLite#10]
Operating system and version: Windows 10 x64, .NET Framework 4.7.2.
Issue encountered: Unhandled System.NullReferenceException in `ClientConnected` event handler that cause application crash.
Expected behavior: Avoiding critical exception that cause application crash.

Exception details:
According to `ClientConnected()` [line: 415] we could encounter an exception before `HttpContext` will be created (region Retrieve-Headers), but in general catch block there is no null check for `ctx` object.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=HttpServerLite
  StackTrace:
   at HttpServerLite.Webserver.<ClientConnected>d__43.MoveNext() in ...\HttpServerLite\Webserver.cs:line 683
```

**Comment by jchristn** [comment]
Thanks @SaintedPsycho - just amended this in [v1.2.1.7](https://www.nuget.org/packages/HttpServerLite/1.2.1.7), could you give it a try?

**Comment by SaintedPsycho** [comment]
Hi @jchristn. Seems like exception is gone. Thank you.
