### ISSUE TITLE
Isn't possible access the disposed object

### ISSUE THREAD

**Issue by marcussacana** [jchristn/HttpServerLite#13]
While debugging a had this error many times, why this happen? maybe is the client closing the connection?
The error description is in portuguese, and means: Isn't possible access the disposed object
![image](https://user-images.githubusercontent.com/10576957/151634979-e4250fb9-029c-4b06-b3dc-a69bdad39e19.png)
![image](https://user-images.githubusercontent.com/10576957/151634999-a6d9adbd-e238-4c49-b3fe-ab872ac11402.png)
![image](https://user-images.githubusercontent.com/10576957/151635089-21859b6a-034d-4158-a5ea-2cea2045b9c6.png)

The headers of the response is this: 
![image](https://user-images.githubusercontent.com/10576957/151635181-4eb17f23-5f67-42db-beaf-bc815f3e6b12.png)

**Comment by marcussacana** [comment]
Since I suspected that for some reason the client closed the connection before get the response body, I tried use wireshark to check the request result.

I don't use wireshark usually then I really don't know, but he said in the response 'illegal segments', maybe that is related with the error?
![image](https://user-images.githubusercontent.com/10576957/151653606-d29129f5-ca5f-4690-be92-2d1b14f549e8.png)

Wireshark dump:
[dump.txt](https://github.com/jchristn/HttpServerLite/files/7963266/dump.txt)

**Comment by jchristn** [comment]
Hi @marcussacana the ```[Illegal Segments]``` is Wireshark's attempts to decode HTTP response data.  If the content isn't full, it can't parse it, and thus it will consider it to be invalid.  Also what is the ```content-type``` header you are returning?

As far as the object disposed exception, yes, if the underlying socket has been closed or terminated, then this will occur.  I will add it to my list to encapsulate in a try/catch block accordingly.  Thanks for bringing it up.

**Comment by marcussacana** [comment]
I think the mime type should be `application/octet-stream`, yeah, looks like I forgot to add this header anyway....

**Comment by jchristn** [comment]
Hi @marcussacana in looking at the code I'm not seeing a clean way to do this *unless* I introduce a new set of APIs hanging off of ```HttpResponse``` so that it can return a ```bool```, such as ```TrySend```, ```TrySendAsync```, etc.  These could return ```Task<bool>``` as opposed to ```Task```.  Thoughts?  Sorry for the delay.

**Comment by marcussacana** [comment]
Looks good, thanks.
