### ISSUE TITLE
Disconnect when a connection is received

### ISSUE THREAD

**Issue by Return25** [jchristn/HttpServerLite#15]
Can a connection be blocked when it is received? (before parsing HTTP data)
I have tried `server.Routes.PreRouting` , but the data has been already parsed when the method is called
btw, I think it is a great project!

**Comment by jchristn** [comment]
Hi @Return25 thanks for your kind words!  HttpServerLite uses [CavemanTcp](https://github.com/jchristn/cavemantcp) under the hood.  CavemanTcp does *not* provide IP-level filtering, but, I could add this capability using the same implementation I used in WatsonTcp (https://github.com/jchristn/WatsonTcp/blob/9c4880ea728260800cfdf95bfecc6ca674383749/WatsonTcp/WatsonTcpServerSettings.cs#L114) if this would be of value to you.  Let me know!

**Comment by Return25** [comment]
Yeah, I need a callback. Please add this feature. Thanks!

**Comment by Return25** [comment]
> Hi @Return25 thanks for your kind words! HttpServerLite uses [CavemanTcp](https://github.com/jchristn/cavemantcp) under the hood. CavemanTcp does _not_ provide IP-level filtering, but, I could add this capability using the same implementation I used in WatsonTcp (https://github.com/jchristn/WatsonTcp/blob/9c4880ea728260800cfdf95bfecc6ca674383749/WatsonTcp/WatsonTcpServerSettings.cs#L114) if this would be of value to you. Alternatively, I could add a callback that could be used to permit/deny a connection upon receipt, supplying the IP and port information, prior to parsing for HTTP data. Let me know if either of these would work for you!

Yeah, I need a callback. Please add this feature. Thanks!

**Comment by jchristn** [comment]
Please give this a try and re-open if there are any issues!

Commit: https://github.com/jchristn/HttpServerLite/commit/824e0a35b8243ed316c9578cc03415908c7a1c73
NuGet: https://www.nuget.org/packages/HttpServerLite/1.2.2

Updated the README with an example, and also added the ```Test.ConnectionAuthorization``` project which implements this. 

Cheers, Joel
