### ISSUE TITLE
System.IO.IOException: "Unable to write data to the transport connection"

### ISSUE THREAD

**Issue by Brendibek** [jchristn/HttpServerLite#16]
An error occurs while the web server is running System.IO.IOException: "Unable to write data to the transport connection", and the program stops its work. This error points to the Webserver class, method ClientConnected, line 714 await ctx.Response.SendAsync(_Pages.Default500Page.Content, _Token).ConfigureAwait(false);.
I checked the error on different versions, including the version compiled from github (05.05.2022). No error on versions 1.0.0.16 -> 1.0.6.1. The error starts to appear from version 1.1.0.1 -> 1.2.2.

**Comment by jchristn** [comment]
Hi @Brendibek some questions for you:

1) which operating system are you using?
2) which runtime are you using?
3) under which circumstances does this happen?
4) does the ```Test``` project work for you?

Thanks!  Joel

**Comment by nimadeuser** [comment]
[布伦迪贝克](https://github.com/Brendibek) 这位朋友说得对  从浏览器过来的请求  服务端会收到两次请求  因为有个预检请求  快速刷新浏览器  会导致服务端崩溃  报错 System.IO.IOException：“无法将数据写入传输连接”  这位朋友提到的版本我也测试过了  确实是这样  希望大佬更新一下

**Comment by nimadeuser** [comment]
The friend is right. The server will receive two requests from the browser, because a pre check request to refresh the browser quickly will cause the server to crash and report an error system IO. IOException: "unable to write data to the transmission connection". I have also tested the version mentioned by this friend. It is true. I hope the boss can update it

**Comment by jchristn** [comment]
Hi all, I've been unable to reproduce this.  For example, in the ```Test``` project, the browser's preflight (```OPTIONS``` request) is followed immediately by a ```GET```, and no exception is thrown.  Can anyone share a very small solution or source code that reproduces this?
```
C:\Code\Misc\HttpServerLite\Test\bin\Debug\net6.0>test
Initializing server
[HttpServerLite http://localhost:8080] adding static route GET /static
[HttpServerLite http://localhost:8080] adding static route GET /static/1
[HttpServerLite http://localhost:8080] adding static route GET /static/2
[HttpServerLite http://localhost:8080] adding static route GET /mirror
[HttpServerLite http://localhost:8080] adding static route GET /mirror/1
[HttpServerLite http://localhost:8080] adding static route GET /mirror/2
[HttpServerLite http://localhost:8080] adding parameter route GET /{version}/api/{id}
[HttpServerLite http://localhost:8080] adding dynamic route GET ^/dynamic/\d+$
Server started
Started on http://localhost:8080
Command [? for help]: [HttpServerLite http://localhost:8080] default route for [::1]:63963 GET /
[HttpServerLite http://localhost:8080] [::1]:63963 GET /: 200 [34.3447ms]
[HttpServerLite http://localhost:8080] default route for [::1]:63964 GET /favicon.ico
[HttpServerLite http://localhost:8080] [::1]:63964 GET /favicon.ico: 200 [88.5357ms]
```
![image](https://user-images.githubusercontent.com/1421081/170055245-7e97aeb7-541b-42c8-bc7e-4c58809e5411.png)

**Comment by jchristn** [comment]
Please re-open if the issue persists and you can provide more detail to help reproduce the issue.

**Comment by imsoo** [comment]
Hi, Thank you for your great project.

I've found that reproduce way about similar exception.

- Run `Test` project.
- Open terminal and input `curl http://localhost:8080/wait`
- Press CTRL-C (Before 10 seconds passed)
- Exception ocurred. (Unhandled exception. System.IO.IOException: Unable to write data to the transport connection)

Thanks!
