### ISSUE TITLE
Large Memory Allocation?

### ISSUE THREAD

**Issue by marcussacana** [jchristn/HttpServerLite#17]
While debugging memory leak in my program, I noticied the HttpServerLite using 3gb of RAM, take a look:
![image](https://user-images.githubusercontent.com/10576957/169274476-d62bd358-9ec8-47d8-b41c-371ad00c9a30.png)
I'm suspecting the GC are being lazy to clean the byte[] that the HttpServerLite discard each loop in the stream copy.
Maybe should be better keep the same buffer variable to the entire stream copy?
Maybe call GC.Collect()?

**Comment by jchristn** [comment]
Hi @marcussacana thanks for the detailed information.  Let me take a look right now.  Thanks!

**Comment by jchristn** [comment]
Could you give it a try with v1.2.3 and let me know if it works?

NuGet: https://www.nuget.org/packages/HttpServerLite/1.2.3
Commit: https://github.com/jchristn/HttpServerLite/commit/5853f68b11905a56502b0739b70575f2aec432d2

**Comment by marcussacana** [comment]
Not yet...
![image](https://user-images.githubusercontent.com/10576957/169405422-01ba8f27-7206-4ec8-a87f-cef92e09acf4.png)

I tried change the code by only creating a new byte[] in the final loop like this:
```csharp
byte[] buffer = new byte[_StreamBufferSize];
while (bytesRemaining > 0)
{
    if (bytesRemaining < _StreamBufferSize)
        buffer = new byte[bytesRemaining];

    int bytesRead = await stream.ReadAsync(buffer, 0, buffer.Length, token).ConfigureAwait(false);
    if (bytesRead > 0)
    { 
        await _Stream.WriteAsync(buffer, 0, bytesRead, token).ConfigureAwait(false);
        bytesRemaining -= bytesRead;
    }
}
```
And the final allocation in the same usage that I did before has only 400mb
![image](https://user-images.githubusercontent.com/10576957/169411194-def05025-c367-4f9c-848c-fb7da2885ffa.png)

**Comment by jchristn** [comment]
Hi @marcussacana I made some additional changes to reduce the memory consumption due to re-initialization.  I'm very sorry for the delay on this, just been overwhelmed lately :)  Could you give it a run and re-open if this doesn't resolve the issue?

NuGet: https://www.nuget.org/packages/HttpServerLite/1.2.9
Commit: https://github.com/jchristn/HttpServerLite/commit/1b832353b295e61117cfa174ce3b226ca7630460

**Comment by marcussacana** [comment]
Fine, I will test when possible, thanks!
