### ISSUE TITLE
Handling TCP Connections

### ISSUE THREAD

**Issue by Return25** [jchristn/HttpServerLite#20]
Hi, I created a server using this library, but some malicious people hacked my server.
Instead of upgrading the connection to an HTTP connection, they only use the TCP protocol and send spam to consume server resources.

So, is there any way to solve this problem?
For example, can I detect and close connections that haven't been upgraded to HTTP for a long time?

**Comment by jchristn** [comment]
Hi there, you should be able to set ```Settings.IO.MaxIncomingHeadersSize```.  It's default value is 64KB.  If they send more than 64KB, the connection should be torn down.

**Comment by Return25** [comment]
Thank you. And is there any event to fire when the connection is torn down? I need to know the IP Address of the connection.

**Comment by facilrapido** [comment]
System.TypeLoadException
  HResult=0x80131522
  Message=Não foi possível carregar o tipo HttpServerLite.HttpContext do assembly HttpServerLite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
  Source=<Não é possível avaliar a origem da exceção>
  StackTrace:
<Não é possível avaliar o rastreamento da pilha de exceção>
