### ISSUE TITLE
Set-Cookies Header

### ISSUE THREAD

**Issue by Jump-Suit** [jchristn/HttpServerLite#25]
I have enjoyed implementing this piece of library code to my project for what I need, my only hiccup is proper handling of the  `Set-Cookie` header, from httpresponse.cs this isn't present, but for headers themselves they get handled as a dictionary{string, string} by [RF6265](https://www.rfc-editor.org/rfc/rfc6265#section-3) origin server is allowed multiple `Set-Cookie` headers, but I am unable to easily achieve this currently!

**Comment by jchristn** [comment]
Hi, thanks for your note.  To make sure I understand, you'd like to have multiple key-value pairs with the key ```Set-Cookie```?  If that's the case, I could convert from a ```Dictionary``` to a ```NameValueCollection```.  Is that the desired behavior?

**Comment by jchristn** [comment]
Hi @Jump-Suit thanks for the suggestion on this, I just updated and released v2.0.0 on NuGet.  Please re-open if this doesn't help your issue.  Cheers, Joel

NuGet: https://www.nuget.org/packages/HttpServerLite/2.0.0
Commit: https://github.com/jchristn/HttpServerLite/commit/cb5476ea7aa107bd4d65b75a580dbc315cd9af7e
