### ISSUE TITLE
Can nativeaot be supported

### ISSUE THREAD

**Issue by williamlzw** [jchristn/HttpServerLite#26]
Can nativeaot be supported
![image](https://user-images.githubusercontent.com/11348670/226788201-71d5feea-f46d-4d30-b74d-af149ce421cb.png)

**Comment by jchristn** [comment]
Maybe; try cloning source and removing this property from ```Webserver.cs```: https://github.com/jchristn/HttpServerLite/blob/cb5476ea7aa107bd4d65b75a580dbc315cd9af7e/src/HttpServerLite/Webserver.cs#L143

**Comment by williamlzw** [comment]
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/
![image](https://user-images.githubusercontent.com/11348670/226796154-2363a465-d24f-4206-adca-28c17efe506c.png)

**Comment by jchristn** [comment]
Hi @williamlzw please see my response to the issue of the same name you filed on Watson Webserver.  Seems like it could work, however, routing would not, and there may be other incompatibilities that would need to be addressed.
