### ISSUE TITLE
About the complete request path does not work

### ISSUE THREAD

**Issue by sqlnew** [jchristn/HttpServerLite#8]
When the original request string submitted by the client is a complete URI address, httpserverlite will not work normally. By checking the source code, it is found that only relative paths are supported when processing request paths, and there is no corresponding processing for complete URI format paths. The tested web servers of IIS or Tomcat support the full format URI

-----------------------------------------------------------------

For example, the following raw string requests are not supported:

GET https://127.0.0.1:7550/test/index.html HTTP/1.1

Host: 127.0. 0.1:7550

Connection: keep-alive

Cache-Control: max-age=0

Upgrade-Insecure-Requests: 1

User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0. 4664.110 Safari/537.36

Accept: text/html,application/xhtml+xml,application/xml; q=0.9,image/avif,image/webp,image/apng,*/*; q=0.8,application/signed-exchange; v=b3; q=0.9

Accept-Encoding: gzip, deflate

Accept-Language: zh-CN,zh; q=0.9

-----------------------------------------------------------------

However, the following original string request works

GET /test/index. html HTTP/1.1

Host: 127.0. 0.1:7550

Connection: keep-alive

Cache-Control: max-age=0

Upgrade-Insecure-Requests: 1

User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0. 4664.110 Safari/537.36

Accept: text/html,application/xhtml+xml,application/xml; q=0.9,image/avif,image/webp,image/apng,*/*; q=0.8,application/signed-exchange; v=b3; q=0.9

Accept-Encoding: gzip, deflate

Accept-Language: zh-CN,zh; q=0.9

-----------------------------------------------------------------

I hope httpserverlite can support full URI addresses to better meet the needs of various scenarios. thank you!

**Comment by jchristn** [comment]
Hi @sqlnew when you say "httpserverlite will not work normally", what is the expected behavior that you are not seeing?  Thanks!

**Comment by sqlnew** [comment]
The main reason for this problem is that when the address of the request sent by the client is a full URI address, httpserverlite still processes the file name of the request according to the relative path, resulting in the inability to access the local file and using the default processing route. I can solve this problem by modifying the source code as follows, and  hope the author can add similar solutions to the source code.
HttpRequest. cs=>private void Build()

                    string[] requestLine = headers[i].Trim().Trim('\0').Split(' ');
                    if (requestLine.Length < 3) throw new ArgumentException("Request line does not contain at least three parts (method, raw URL, protocol/version).");

                    //Analyze relative paths//
                    string TemReqestUrl = requestLine[1];
                    string TemPath = "";
                    if(TemReqestUrl.ToLower().StartsWith("http"))
                    {
                        var modifiedUri = new UriBuilder(TemReqestUrl);
                        TemPath = modifiedUri.Path;
                        modifiedUri = null;
                    }
                    else{
                        TemPath = TemReqestUrl;
                    }

                    Method = (HttpMethod)Enum.Parse(typeof(HttpMethod), requestLine[0], true);
                    Url = new UrlDetails(TemPath);
                    Query = new QueryDetails(requestLine[1]);
                    ProtocolVersion = requestLine[2];

**Comment by jchristn** [comment]
I appreciate the succinct fix!  Please confirm this is resolved in 1.2.1.5: https://www.nuget.org/packages/HttpServerLite/1.2.1.5.  Also adding you to the README as a contributor.  Thanks for your help!
